name: Build Pages
on:
  push:
    branches:
      - develop
      - main
      - 'pwx-**'
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install Bun dependencies
        run: bun install
        working-directory: ./
      - run: pip install zensical
      - name: Run Bun build
        run: bun run build
        working-directory: ./
      - uses: actions/upload-pages-artifact@v4
        with:
          path: .zensical/site/
      - uses: actions/deploy-pages@v4
